name: hc-cv
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - pandas
  - nltk
  - torchinfo
  - pip
  - pytorch_lightning
  - pip:
      - wandb
      - torchinfo
