name: hc-cv
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - pandas
  - nltk
  - pip
  - pytorch_lightning
  - rich
  - pip:
      - wandb
      - robustness
      - rich
      - pyarrow
